# k8s-manifests-lint configuration file

# Sources configuration
# If no sources are specified, the tool will use YAML renderer on paths provided via CLI
sources:
  # Example: YAML files
  #- type: yaml
  #  path: ./manifests

  # Example: Kustomize
  - type: kustomize
    path: ./docs/examples

  # Example: Helm chart
  # - type: helm
  #   chart: oci://registry.example.com/my-chart:1.0.0
  #   data:
  #     namespace: default
  #     releaseName: my-release
  #     replicaCount: 3
  #     image:
  #       repository: nginx
  #       tag: "1.21"

  # Example: Go templates
  # - type: gotemplate
  #   path: "templates/*.yaml"
  #   data:
  #     environment: production
  #     replicas: 3

# Linters configuration
linters:
  enable:
    - resource-limits
    - security-context
    - required-labels
    - health-probes
    - image-tags
    - cluster-role-binding-security

  disable: []

  # Per-linter settings
  settings:
    resource-limits:
      require-cpu-limit: true
      require-memory-limit: true
      require-cpu-request: true
      require-memory-request: true
      exclude-namespaces:
        - kube-system

    required-labels:
      labels:
        - app
        - version
      exclude-kinds:
        - ConfigMap
        - Secret

    security-context:
      require-run-as-non-root: true
      require-read-only-root-filesystem: false
      disallow-privilege-escalation: true
      required-dropped-capabilities:
        - ALL

    health-probes:
      require-liveness: true
      require-readiness: true
      exclude-kinds:
        - Job
        - CronJob

    image-tags:
      disallow-latest: true
      require-digest: false
      allowed-registries:
        - docker.io
        - gcr.io
        - ghcr.io

    cluster-role-binding-security:
      disallowed-groups:
        - system:authenticated
        - system:unauthenticated
        - system:serviceaccounts
      warn-namespace-groups: true
      allowed-roles-for-broad-groups:
        - system:basic-user
        - system:discovery
      critical-roles:
        - cluster-admin
        - admin

# Output configuration
output:
  format: text
  show-source: true
  color: auto

# Run configuration
run:
  skip-dirs:
    - vendor
    - .git
